services:
  nats:
    image: nats:${NATS_VERSION}
    ports:
      - 4222:4222
      - 8222:8222
    command: ["-n", "my-server", "-js", "-sd", "/data", "-p", "4222", "-m", "8222"]
    volumes:
      - nats_data:/data

  nats-cli:
    build:
      context: ./nats-cli
      dockerfile: Dockerfile
      args:
        TTYD_VERSION: latest
        NATS_CLI_VERSION: 0.3.0
    image: arulrajnet/nats-cli:0.3.0
    environment:
      NATS_URL: nats://nats:4222
    depends_on:
      - nats
    ports:
      - "7681:7681"
    volumes:
      - nats_cli_data:/data

  nats-dashboard:
    image: mdawar/nats-dashboard:${NATS_DASHBOARD_VERSION}
    ports:
      - "8000:80"
    environment:
      REVERSE_PROXY_UPSTREAM: 'nats:8222'
    configs:
      - source: config.json
        target: /srv/config.json

configs:
  config.json:
    content: |
      {
        "server": {
          "name": "my-server",
          "url": "http://localhost:8000/proxy/"
        },
        "hideServerInput": true
      }

volumes:
  nats_data:
  nats_cli_data:
